name: Secret Secret

on:
  push:
    branches:
      - main

jobs:
  fetch-secret:
    runs-on: ubuntu-latest

    env:
      HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
      HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
      HCP_LOCATION: "https://api.cloud.hashicorp.com/secrets/2023-11-28/organizations/6683972e-be8c-4e46-92f8-b299e1ad7674/projects/120c304b-9f4d-4d10-a0f6-8ec1d2f0fa19/apps/cloudTech/secrets:open"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq for JSON parsing
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch secret from HashiCorp Vault
        run: |
          echo "Fetching secret from HashiCorp Vault..."

          HCP_API_TOKEN=$(curl --location "https://auth.idp.hashicorp.com/oauth2/token" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "client_id=$HCP_CLIENT_ID" \
            --data-urlencode "client_secret=$HCP_CLIENT_SECRET" \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "audience=https://api.hashicorp.cloud" | jq -r .access_token)

          SECRET_RESPONSE=$(curl -s --request GET \
            --url "$HCP_LOCATION" \
            --header "Authorization: Bearer $HCP_API_TOKEN")

          set +x
          SECRET_APP=$(echo "$SECRET_RESPONSE" | jq -r '.secrets[] | select(.name == "SECRET_APP") | .static_version.value')
          echo "::add-mask::${SECRET_APP}"
          set -x

          if [ -z "$SECRET_APP" ]; then
            echo "Ошибка: SECRET_APP не найден"
            exit 1
          fi

          echo "SECRET_APP=***" >> $GITHUB_ENV

      - name: Use the secret
        run: |
          set +x
          echo "Using the fetched secret..." > secret.txt
          cat secret.txt
          set -x
          echo "Secret used successfully."
